# This compose file is meant for development purposes.

services:
  moodle-api:
    container_name: MoodlewareAPI
    build: .
    ports:
      - ${PORT-8000}:8000
    restart: unless-stopped
    env_file:
      - .env
