# This compose file is meant for development purposes.

services:
  moodle-api:
    container_name: MoodlewareAPI
    build: .
    ports:
      - ${PORT-8000}:8000
    environment:
      - MOODLE_URL=${MOODLE_URL}
      - ALLOW_ORIGINS=${ALLOW_ORIGINS}
      - LOG_LEVEL=${LOG_LEVEL}
    restart: unless-stopped
